export const LOGIN_AUTH_REQUEST = "LOGIN_AUTH_REQUEST";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAIL = "LOGIN_AUTH_FAIL";

export const REGISTER_AUTH_REQUEST = 'LOGIN_AUTH_REQUEST';
export const REGISTER_AUTH_SUCCESS = 'LOGIN_AUTH_SUCCESS';
export const REGISTER_AUTH_FAIL = 'LOGIN_AUTH_FAIL';

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_FAIL_REQUEST'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const ADMIN_OTP_REQUESST = 'ADMIN_OTP_REQUESST';
export const ADMIN_OTP_SUCCESS = 'ADMIN_OTP_SUCCESS';
export const ADMIN_OPT_FAIL = 'ADMIN_OPT_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const REST_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const REST_PASSWORD_FAIL = 'REST_PASSWORD_FAIL'

export const CLEAR_DATA = "CLEAR_DATA";