export const LOGIN_AUTH_REQUEST = "LOGIN_AUTH_REQUEST";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAIL = "LOGIN_AUTH_FAIL";

export const REGISTER_AUTH_REQUEST = 'LOGIN_AUTH_REQUEST';
export const REGISTER_AUTH_SUCCESS = 'LOGIN_AUTH_SUCCESS';
export const REGISTER_AUTH_FAIL = 'LOGIN_AUTH_FAIL';

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_FAIL_REQUEST'

export const CLEAR_DATA = "CLEAR_DATA";