export const ALL_PACKAGE_REQUEST = "ALL_PACKAGE_REQUEST";
export const ALL_PACKAGE_SUCCESS = "ALL_PACKAGE_SUCCESS";
export const ALL_PACKAGE_FAIL = "ALL_PACKAGE_FAIL";

export const CREATE_PACKAGE_REQUEST = "CREATE_PACKAGE_REQUEST";
export const CREATE_PACKAGE_SUCCESS = "CREATE_PACKAGE_SUCCESS";
export const CREATE_PACKAGE_FAIL = "CREATE_PACKAGE_FAIL";

export const ONE_PACKAGE_REQUEST = "ONE_PACKAGE_REQUEST";
export const ONE_PACKAGE_SUCCESS = "ONE_PACKAGE_SUCCESS";
export const ONE_PACKAGE_FAIL = "ONE_PACKAGE_FAIL";

export const UPDATE_PACKAGE_REQUEST = "UPDATE_PACKAGE_REQUEST";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_FAIL = "UPDATE_PACKAGE_FAIL";

export const DELETE_PACKAGE_REQUEST = "DELETE_PACKAGE_REQUEST";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_FAIL = "DELETE_PACKAGE_FAIL";

export const CLEAR_DATA = "CLEAR_DATA";