export const ALL_USER_REQUEST = "ALL_USER_REQUEST";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";

export const ONE_USER_REQUEST = "ONE_USER_REQUEST";
export const ONE_USER_SUCCESS = "ONE_USER_SUCCESS";
export const ONE_USER_FAIL = "ONE_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const USER_OTP_REQUEST = "GET_USER_OTP"
export const USER_OPT_SUCCESS = "USER_OPT_SUCCESS"
export const USER_OPT_FAIL = "USER_OPT_FAIL"

export const CLEAR_DATA = "CLEAR_DATA";